### ISSUE TITLE
Won't download

### ISSUE THREAD

**Issue by Harlequin8808** [bartoffw/instabook#1]
Hi, some pages won't download. The preview loads and I can click on the download button, but nothing happens. This is completely random, and there isn't a pattern that I can discern. Any help is appreciated.

**Comment by bartoffw** [comment]
Can you give some example pages? This week help me checking what's specific with them and fix the problem.
Some pages don't have content or have dynamic content so may not always load.

**Comment by Harlequin8808** [comment]
Hi, here are they:
https://www.writerswrite.co.za/a-complete-glossary-of-terms-for-fantasy-writers/
https://www.writerswrite.co.za/fantasy-book-title-generator/

It's very strange. It's only a couple of pages that this has happened to.

**Comment by bartoffw** [comment]
I noticed this is happening only on Chrome browser, the extension on Firefox works without problems on that page. I'm going to take a look what's causing this and will update you here.

**Comment by bartoffw** [comment]
@Harlequin8808 I just published an updated version of the extension for all browsers - v1.1.1. It has improved handling of images, especially the ones that time out or load very slowly which may cause the problem with downloading of the epub file. The ebook generation with images will be more reliable now. Please let me know if you still have any issues with the latest version.

**Comment by bartoffw** [comment]
Marking this issue as closed for now as there was no response for over a week.
